# Generated by Django 3.2.2 on 2021-05-24 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Content name')),
                ('series', models.IntegerField(default=1, verbose_name='Content series')),
                ('season', models.IntegerField(default=1, verbose_name='Content season')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Content date')),
                ('views', models.IntegerField(default=0, verbose_name='Content views')),
                ('path', models.URLField(verbose_name='Content path')),
                ('cover', models.URLField(verbose_name='Content background')),
                ('duration', models.IntegerField(default=1, verbose_name='Content duration')),
            ],
        ),
    ]
