# Generated by Django 3.2.2 on 2021-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default='', verbose_name='Content description'),
        ),
    ]
