# Generated by Django 3.2.2 on 2021-05-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='series_name',
            field=models.TextField(default='', verbose_name='Content series name'),
        ),
    ]
